--SELECT (DATA QUERY LANGUAGE)
    --SYNTAX FOR MULTIPLE COLUMNS
        -- SELECT COLUMN1,COLUMN2 FROM tableName;
    SELECT EMPFNAME,EMPCODE,EMPLNAME FROM EMPLOYEE;
    --SYNTAX FOR SELECTING EVERYTHING
        -- SELECT * FROM tableName
     SELECT * FROM EMPLOYEE;
     
     --CLAUSES
       -- WHERE(FOR PUTTING CONDITIONS)
       -- ORDER BY
       -- GROUPBY
       -- HAVING

            --SYNTAX
            SELECT * FROM EMPLOYEE
            WHERE SALARY > 2800;
----MANAGER CODE 7566
     SELECT EMPFNAME,EMPLNAME,DEPTCODE FROM employee
        WHERE MANAGERCODE=7566;


            --OPERATORS:
                    --COMPARISON : =,>,<,>=,<=,
                    -- <> -> NOT EQUALS
    ----------------------------------------
    -- ORDER BY -> USED FOR ORDERING ON THE BASIS OF COLUMN
    -- BY DEFAULT ORDERING ASCENDING
             SELECT * FROM employee 
                 ORDER BY SALARY; 
        
        --DESCENDING ORDER 
            SELECT * FROM employee 
                ORDER BY SALARY DESC; 
        -- IN THE CASE OF COMMON ORDER DATA AFTER DESC COMMA U CAN ASSIGN THAT COMMON DATA TOO..AS DEPTCODE IS DIFFERENT
            SELECT * FROM employee
                ORDER BY SALARY DESC, DEPTCODE ASC;

 --AGGREGATE FUNCTIONS : COUNT,AVG,SUM,MAX,MIN

-- COUNT NO. OF EMPLOYESS
    SELECT COUNT(*) FROM employee;

-- COUNT AVERAGE SALARY
    SELECT AVG(SALARY) FROM employee;
-- HIGHEST EARNER DATA
    SELECT MAX(SALARY) FROM employee;
-- MIN SALARY
    SELECT MIN(SALARY) FROM employee;
-- TOTAL SALARY
SELECT SUM(SALARY) FROM employee;
--------------------------------------------------------------------------------------------------------------
 -- GROUPBY -  HUME UNIQUE EK HI VALUE LAKE DENGA 
                --for eg- deptcode mai - 10,10,10 ,20,30 same code hone ke baad bhi hume ek hi code lake denga
                -- and uske upar hum aggregate functions laga sakte hai
    
    --SCENARIOS 
    --GROUP BY ON THE BASIS OF DEPTCODE
    SELECT DEPTCODE AS "COUNT PER DEP"
     FROM employee
	    GROUP BY DEPTCODE;

    --COUNT NUMBER OF EMPLOYEES IN EACH DEPTCODE
    SELECT DEPTCODE,COUNT(DEPTCODE) FROM employee
	    GROUP BY DEPTCODE;

    -- CALCULATE MAXIMUM SALARY DEPARTMENT WISE 
    SELECT DEPTCODE,MAX(SALARY)AS "SALARY",COUNT(DEPTCODE) AS "DEPT", FROM employee
	    GROUP BY DEPTCODE;

    -- HAVING : WORKS ON THE AGGREGATE FUNCTION ONLY
    --          : USED TO ADD CONDITION ON GROUP BY
    SELECT DEPTCODE,MIN(SALARY) FROM employee
    GROUP BY DEPTCODE
    HAVING MIN(SALARY > 2000);
    

    -- QUE : DESIGNATION TELL ME WHAT IS THE HIGHEST SALARY
      --      I ALSO DONT WANT DATA OF DEPTCODE 20

      SELECT DESIGNATION,
      COUNT(DESIGNATION) AS "COUNT PER DEP",
      MAX(SALARY) AS "MAX SALARY" FROM employee
      WHERE DEPTCODE <>20
      GROUP BY DESIGNATION

    -- QUE : DESIGNATION TELL ME WHAT IS THE HIGHEST SALARY
      --      I ALSO DONT WANT DATA OF SALESEMAN 
      SELECT DESIGNATION,
      COUNT(DESIGNATION) AS "COUNT PER DAY",
      MAX(SALARY) AS"MAX SALARY" FROM employee
      WHERE DESIGNATION <> "SALESMAN" 
      GROUP BY DESIGNATION

    -- QUE : DESIGNATION TELL ME WHAT IS THE HIGHEST SALARY
      --      I ALSO DONT WANT DATA OF SALSEMAN
      --   AND MAX SALARIES DEPT WISE SHOULD BE GREATER THEN 3000

      SELECT DESIGNATION,
      COUNT(DESIGNATION) AS "COUNT PER DAY",
      MAX(SALARY) AS"MAX SALARY" FROM employee
      WHERE DESIGNATION <> "SALESMAN" 
      GROUP BY DESIGNATION
      HAVING MAX(SALARY)>3000
      ORDER BY MAX(SALARY);

      -- QUE : GIVE ME THE AVG SALARIES OF THE EMPLOYEES 
        -- DEPTCODE WISE WHERE NUMBER OF EMPLOYEES IS MORE THAN 2 
        -- IN INCREASING ORDER??
    SELECT DEPTCODE ,COUNT(DEPTCODE),AVG(SALARY)
    FROM employee
    GROUP BY DEPTCODE
    HAVING COUNT(DEPTCODE)>2
    ORDER BY AVG(SALARY)
